---
plugins:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
exclude_patterns:
- dist/**/*
- config/
- db/
- dist/
- features/
- script/
- test/
- fixtures/
- tests/
- node_modules/
- client/