---
plugins:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
exclude_patterns:
- dist/**/*
- server/config/
- db/
- dist/
- features/
- script/
- server/test/
- server/fixtures/
- server/tests/
- node_modules/
- client/
